using LiteNetLib.Utils;
namespace Content.Shared.Network;
public static partial class NetworkProtocol
{
    public static bool ValidEconomyCommand(EconomyCommand v)
    {
        if(v.Operation is 0 or >long.MaxValue || !Enum.IsDefined(v.Action) || v.QuoteId>long.MaxValue || v.ItemRevision>long.MaxValue || v.ListingId>long.MaxValue || v.Price is <0 or >1000000 || v.Quantity>999)return false;
        return v.Action switch {
            EconomyAction.Evolve or EconomyAction.Enhance=>v.ItemHandle>0&&v.ItemRevision>0&&v.ListingId==0&&v.Quantity==0&&v.Price==0,
            EconomyAction.List=>v.ItemHandle>0&&v.ItemRevision>0&&v.ListingId==0&&v.Quantity==0&&v.Price>0,
            EconomyAction.Buy or EconomyAction.Cancel=>v.ItemHandle==0&&v.ItemRevision==0&&v.ListingId>0&&v.Quantity==0&&v.Price==0,
            EconomyAction.SellOre=>v.ItemHandle==0&&v.ItemRevision==0&&v.ListingId==0&&v.Quantity>0&&v.Price==0,
            EconomyAction.Claim=>v.ItemHandle==0&&v.ItemRevision==0&&v.ListingId==0&&v.Quantity==0&&v.Price==0,
            _=>false};
    }
    private static void PutEconomyCommand(NetDataWriter w,EconomyCommand v){w.Put(v.Operation);w.Put((byte)v.Action);w.Put(v.ItemHandle);w.Put(v.ItemRevision);w.Put(v.ListingId);w.Put(v.Quantity);w.Put(v.Price);w.Put(v.QuoteId);}
    private static bool ReadEconomyCommand(NetDataReader r,out EconomyCommand v)
    {v=default;if(!r.TryGetULong(out var op)||!r.TryGetByte(out var action)||!r.TryGetULong(out var item)||!r.TryGetULong(out var rev)||!r.TryGetULong(out var listing)||!r.TryGetUShort(out var qty)||!r.TryGetInt(out var price)||!r.TryGetULong(out var quote))return false;var n=new EconomyCommand(op,(EconomyAction)action,item,rev,listing,qty,price,quote);if(!ValidEconomyCommand(n))return false;v=n;return true;}
    public static NetDataWriter Write(EconomyCommand v){if(!ValidEconomyCommand(v))throw new ArgumentException("Invalid economy intention.");var w=CreateWriter(NetworkMessageType.EconomyCommand);PutEconomyCommand(w,v);return w;}
    public static bool TryReadEconomyCommand(NetDataReader r,out EconomyCommand v){v=default;return r.AvailableBytes==47&&ReadEconomyCommand(r,out v)&&r.AvailableBytes==0;}
    private static bool ValidEconomyQuote(EconomyQuote v)=>ValidEconomyCommand(v.Command)&&v.Command.QuoteId>0&&v.Chance<=100&&v.DurabilityLoss<=1000&&v.OutputName is {Length:<=24}&&System.Text.Encoding.UTF8.GetByteCount(v.OutputName)<=48&&double.IsFinite(v.AttackGain)&&v.AttackGain is >=0 and <=1000&&v.CoinChange is >=-1000000 and <=1000000&&float.IsFinite(v.ValidSeconds)&&v.ValidSeconds is >0 and <=15&&TradeAmounts(v.Costs);
    public static NetDataWriter Write(EconomyQuote v){if(!ValidEconomyQuote(v))throw new ArgumentException("Invalid economy quote.");var w=CreateWriter(NetworkMessageType.EconomyQuote);PutEconomyCommand(w,v.Command);w.Put(v.ServerTick);w.Put(v.Chance);w.Put(v.DurabilityLoss);w.Put(v.OutputName);w.Put(v.AttackGain);w.Put(v.CoinChange);w.Put(v.ValidSeconds);PutTradeAmounts(w,v.Costs);return w;}
    public static bool TryReadEconomyQuote(NetDataReader r,out EconomyQuote v){v=default;if(r.AvailableBytes>140||!ReadEconomyCommand(r,out var c)||!r.TryGetUInt(out var tick)||!r.TryGetByte(out var chance)||!r.TryGetUShort(out var loss)||!r.TryGetString(out var name)||!r.TryGetDouble(out var gain)||!r.TryGetInt(out var coins)||!r.TryGetFloat(out var seconds)||!ReadTradeAmounts(r,out var costs)||r.AvailableBytes!=0)return false;var n=new EconomyQuote(c,tick,chance,loss,name,gain,coins,seconds,costs);if(!ValidEconomyQuote(n))return false;v=n;return true;}
    public static NetDataWriter Write(EconomyResult v){if(v.Operation is 0 or >long.MaxValue||!Enum.IsDefined(v.Outcome)||!Enum.IsDefined(v.Effect))throw new ArgumentException("Invalid economy result.");var w=CreateWriter(NetworkMessageType.EconomyResult);w.Put(v.Operation);w.Put(v.ServerTick);w.Put((byte)v.Outcome);w.Put((byte)v.Effect);return w;}
    public static bool TryReadEconomyResult(NetDataReader r,out EconomyResult v){v=default;if(r.AvailableBytes!=14||!r.TryGetULong(out var op)||op is 0 or >long.MaxValue||!r.TryGetUInt(out var tick)||!r.TryGetByte(out var outcome)||!r.TryGetByte(out var effect)||!Enum.IsDefined((CraftOutcome)outcome)||!Enum.IsDefined((EconomyEffect)effect))return false;v=new(op,tick,(CraftOutcome)outcome,(EconomyEffect)effect);return true;}
    private static bool ValidEconomyState(EconomyState v)=>v.OwnerId.IsValid&&v.LastOperation<=long.MaxValue&&v.Coins is >=0 and <=1000000&&Enum.IsDefined(v.LastEffect)&&v.Items is {Count:<=8}&&v.Items.All(i=>i.Handle>0&&i.Revision is >0 and <=long.MaxValue&&i.Enhancement<=5)&&v.Items.Select(i=>i.Handle).Distinct().Count()==v.Items.Count;
    public static NetDataWriter Write(EconomyState v){if(!ValidEconomyState(v))throw new ArgumentException("Invalid economy state.");var w=CreateWriter(NetworkMessageType.EconomyState);w.Put(v.OwnerId.Value);w.Put(v.ServerTick);w.Put(v.LastOperation);w.Put(v.Coins);w.Put((byte)v.LastEffect);w.Put((byte)v.Items.Count);foreach(var i in v.Items){w.Put(i.Handle);w.Put(i.Revision);w.Put(i.Enhancement);}return w;}
    public static bool TryReadEconomyState(NetDataReader r,out EconomyState v){v=default;if(r.AvailableBytes>162||!r.TryGetULong(out var owner)||!r.TryGetUInt(out var tick)||!r.TryGetULong(out var op)||!r.TryGetInt(out var coins)||!r.TryGetByte(out var effect)||!r.TryGetByte(out var count)||count>8)return false;var items=new EconomyItem[count];for(var i=0;i<count;i++){if(!r.TryGetULong(out var h)||!r.TryGetULong(out var rev)||!r.TryGetByte(out var level))return false;items[i]=new(h,rev,level);}if(r.AvailableBytes!=0)return false;var n=new EconomyState(new(owner),tick,op,coins,(EconomyEffect)effect,items);if(!ValidEconomyState(n))return false;v=n;return true;}
    private static bool ValidMarketState(MarketState v)=>v.OwnerId.IsValid&&v.Credit is >=0 and <=1000000&&v.Listings is {Count:<=8}&&v.Listings.All(l=>l.Id is >0 and <=long.MaxValue&&l.Price is >0 and <=1000000&&TradeItemsValid([l.Item]))&&v.Listings.Select(l=>l.Id).Distinct().Count()==v.Listings.Count&&v.Listings.Select(l=>l.Item.Handle).Distinct().Count()==v.Listings.Count;
    public static NetDataWriter Write(MarketState v){if(!ValidMarketState(v))throw new ArgumentException("Invalid market state.");var w=CreateWriter(NetworkMessageType.MarketState);w.Put(v.OwnerId.Value);w.Put(v.ServerTick);w.Put(v.Credit);w.Put((byte)v.Listings.Count);foreach(var l in v.Listings){w.Put(l.Id);w.Put(l.Price);w.Put(l.Own);PutTradeItems(w,[l.Item]);}return w;}
    public static bool TryReadMarketState(NetDataReader r,out MarketState v){v=default;if(r.AvailableBytes>900||!r.TryGetULong(out var owner)||!r.TryGetUInt(out var tick)||!r.TryGetInt(out var credit)||!r.TryGetByte(out var count)||count>8)return false;var listings=new MarketListing[count];for(var i=0;i<count;i++){if(!r.TryGetULong(out var id)||!r.TryGetInt(out var price)||!r.TryGetByte(out var own)||own>1||!ReadTradeItems(r,out var item)||item.Length!=1)return false;listings[i]=new(id,price,own==1,item[0]);}if(r.AvailableBytes!=0)return false;var n=new MarketState(new(owner),tick,credit,listings);if(!ValidMarketState(n))return false;v=n;return true;}
}
