using LiteNetLib.Utils;
namespace Content.Shared.Network;
public static partial class NetworkProtocol
{
    private static bool TradeAmounts(IReadOnlyList<MaterialAmount>? v) => v is {Count:<=4} && CraftAmounts(v);
    private static bool TradeCommandValid(TradeCommand v) => v.Sequence>0 && Enum.IsDefined(v.Action) && v.PartnerId.IsValid && (v.Action==TradeAction.Invite ? v.SessionId==0 : v.SessionId>0) && v.Items is {Count:<=4} && v.Items.All(h=>h!=0) && v.Items.Distinct().Count()==v.Items.Count && TradeAmounts(v.Materials) && (v.Action==TradeAction.Offer || v.Items.Count==0 && v.Materials.Count==0);
    public static NetDataWriter Write(TradeCommand v)
    { if(!TradeCommandValid(v)) throw new ArgumentException("Invalid trade intention."); var w=CreateWriter(NetworkMessageType.TradeCommand); w.Put(v.Sequence); w.Put((byte)v.Action); w.Put(v.SessionId); w.Put(v.PartnerId.Value); w.Put(v.Revision); w.Put((byte)v.Items.Count); foreach(var h in v.Items) w.Put(h); PutTradeAmounts(w,v.Materials); return w; }
    public static bool TryReadTradeCommand(NetDataReader r,out TradeCommand v)
    { v=default; if(r.AvailableBytes>75 || !r.TryGetUInt(out var sequence) || !r.TryGetByte(out var action) || !r.TryGetULong(out var session) || !r.TryGetULong(out var partner) || !r.TryGetUInt(out var revision) || !r.TryGetByte(out var count) || count>4) return false; var handles=new ulong[count]; for(var i=0;i<count;i++) if(!r.TryGetULong(out handles[i])) return false; if(!ReadTradeAmounts(r,out var amounts) || r.AvailableBytes!=0) return false; var value=new TradeCommand(sequence,(TradeAction)action,session,new(partner),revision,handles,amounts); if(!TradeCommandValid(value)) return false; v=value; return true; }
    private static void PutTradeAmounts(NetDataWriter w,IReadOnlyList<MaterialAmount> values) { w.Put((byte)values.Count); foreach(var v in values) { w.Put(v.Id); w.Put(v.Quantity); } }
    private static bool ReadTradeAmounts(NetDataReader r,out MaterialAmount[] values) { values=[]; if(!r.TryGetByte(out var count) || count>4 || r.AvailableBytes<count*4) return false; var items=new MaterialAmount[count]; for(var i=0;i<count;i++) { if(!r.TryGetUShort(out var id) || !r.TryGetUShort(out var quantity)) return false; items[i]=new(id,quantity); } if(!TradeAmounts(items)) return false; values=items; return true; }
    private static bool TradeItemsValid(IReadOnlyList<TradeItem>? values)
    { if(values is not {Count:<=4}) return false; var handles=new HashSet<ulong>(); foreach(var v in values) if(!handles.Add(v.Handle) || !ValidInventoryEntry(new(v.Handle,v.Name,v.Slot,false,v.Attack,v.Defense,v.Health)) || v.Maximum>1000 || v.Current>v.Maximum) return false; return true; }
    private static bool TradeStateValid(TradeState v) => v.OwnerId.IsValid && v.PartnerId.IsValid && v.OwnerId!=v.PartnerId && v.SessionId>0 && v.Revision>0 && Enum.IsDefined(v.Phase) && TradeItemsValid(v.OwnItems) && TradeItemsValid(v.PartnerItems) && TradeAmounts(v.OwnMaterials) && TradeAmounts(v.PartnerMaterials);
    private static void PutTradeItems(NetDataWriter w,IReadOnlyList<TradeItem> values)
    { w.Put((byte)values.Count); foreach(var v in values) { w.Put(v.Handle); w.Put(v.Name); w.Put((byte)v.Slot); w.Put(v.Attack); w.Put(v.Defense); w.Put(v.Health); w.Put(v.Current); w.Put(v.Maximum); } }
    private static bool ReadTradeItems(NetDataReader r,out TradeItem[] values)
    { values=[]; if(!r.TryGetByte(out var count) || count>4) return false; var items=new TradeItem[count]; for(var i=0;i<count;i++) { if(!r.TryGetULong(out var handle) || !r.TryGetString(out var name) || !r.TryGetByte(out var slot) || !r.TryGetDouble(out var atk) || !r.TryGetDouble(out var def) || !r.TryGetDouble(out var hp) || !r.TryGetUShort(out var current) || !r.TryGetUShort(out var maximum)) return false; items[i]=new(handle,name,(EquipmentSlot)slot,atk,def,hp,current,maximum); } if(!TradeItemsValid(items)) return false; values=items; return true; }
    public static NetDataWriter Write(TradeState v)
    { if(!TradeStateValid(v)) throw new ArgumentException("Invalid trade state."); var w=CreateWriter(NetworkMessageType.TradeState); w.Put(v.OwnerId.Value); w.Put(v.ServerTick); w.Put(v.SessionId); w.Put(v.PartnerId.Value); w.Put(v.Revision); w.Put((byte)v.Phase); w.Put(v.OwnAccepted); w.Put(v.PartnerAccepted); PutTradeItems(w,v.OwnItems); PutTradeAmounts(w,v.OwnMaterials); PutTradeItems(w,v.PartnerItems); PutTradeAmounts(w,v.PartnerMaterials); return w; }
    public static bool TryReadTradeState(NetDataReader r,out TradeState v)
    { v=default; if(r.AvailableBytes>800 || !r.TryGetULong(out var owner) || !r.TryGetUInt(out var tick) || !r.TryGetULong(out var session) || !r.TryGetULong(out var partner) || !r.TryGetUInt(out var revision) || !r.TryGetByte(out var phase) || !r.TryGetByte(out var own) || own>1 || !r.TryGetByte(out var other) || other>1 || !ReadTradeItems(r,out var ownItems) || !ReadTradeAmounts(r,out var ownMaterials) || !ReadTradeItems(r,out var partnerItems) || !ReadTradeAmounts(r,out var partnerMaterials) || r.AvailableBytes!=0) return false; var value=new TradeState(new(owner),tick,session,new(partner),revision,(TradePhase)phase,own==1,other==1,ownItems,ownMaterials,partnerItems,partnerMaterials); if(!TradeStateValid(value)) return false; v=value; return true; }
    public static NetDataWriter Write(TradeResult v) { if(v.Sequence==0 || !Enum.IsDefined(v.Outcome)) throw new ArgumentException("Invalid trade result."); var w=CreateWriter(NetworkMessageType.TradeResult); w.Put(v.Sequence); w.Put(v.ServerTick); w.Put((byte)v.Outcome); return w; }
    public static bool TryReadTradeResult(NetDataReader r,out TradeResult v) { v=default; if(r.AvailableBytes!=9 || !r.TryGetUInt(out var seq) || seq==0 || !r.TryGetUInt(out var tick) || !r.TryGetByte(out var result) || !Enum.IsDefined((CraftOutcome)result)) return false; v=new(seq,tick,(CraftOutcome)result); return true; }
}
