using LiteNetLib.Utils;
using System.Numerics;
using System.Text;
namespace Content.Shared.Network;
public static partial class NetworkProtocol
{
    private static bool SocialText(string s)=>s is {Length:<=96}&&Encoding.UTF8.GetByteCount(s)<=96&&!s.Any(char.IsControl);
    public static bool ValidSocialCommand(SocialCommand v)
    {
        if(v.Operation is 0 or >long.MaxValue||!Enum.IsDefined(v.Kind)||!Enum.IsDefined(v.Action)||v.Target>long.MaxValue||v.ExpectedRevision>long.MaxValue||v.Token>long.MaxValue||!SocialText(v.Name))return false;
        return v.Action switch{
            SocialAction.Create=>v.Target==0&&v.ExpectedRevision==0&&v.Token==0&&v.Capacity==0&&!v.Acknowledge&&(v.Kind==SocialKind.Guild||v.Name.Length==0),
            SocialAction.Accept or SocialAction.Decline=>v.Target==0&&v.Token>0&&v.Capacity==0&&v.Name.Length==0&&(v.Action==SocialAction.Accept?v.Acknowledge:!v.Acknowledge),
            SocialAction.Resize=>v.Kind==SocialKind.Party&&v.Target==0&&v.Token==0&&v.Capacity is 6 or 20&&!v.Acknowledge&&v.Name.Length==0,
            SocialAction.Disband=>v.Kind==SocialKind.Guild&&v.Target==0&&v.Token==0&&v.Capacity==0&&v.Acknowledge&&v.Name.Length==0,
            SocialAction.Leave=>v.Target==0&&v.Token==0&&v.Capacity==0&&!v.Acknowledge&&v.Name.Length==0,
            _=>v.Target>0&&v.Token==0&&v.Capacity==0&&!v.Acknowledge&&v.Name.Length==0};
    }
    public static NetDataWriter Write(SocialCommand v){if(!ValidSocialCommand(v))throw new ArgumentException("Invalid social command.");var w=CreateWriter(NetworkMessageType.SocialCommand);w.Put(v.Operation);w.Put((byte)v.Kind);w.Put((byte)v.Action);w.Put(v.Target);w.Put(v.ExpectedRevision);w.Put(v.Token);w.Put(v.Capacity);w.Put(v.Acknowledge);w.Put(v.Name);return w;}
    public static bool TryReadSocialCommand(NetDataReader r,out SocialCommand v){v=default;if(r.AvailableBytes>134||!r.TryGetULong(out var op)||!r.TryGetByte(out var kind)||!r.TryGetByte(out var action)||!r.TryGetULong(out var target)||!r.TryGetULong(out var rev)||!r.TryGetULong(out var token)||!r.TryGetByte(out var cap)||!r.TryGetByte(out var ack)||ack>1||!r.TryGetString(out var name)||r.AvailableBytes!=0)return false;var n=new SocialCommand(op,(SocialKind)kind,(SocialAction)action,target,rev,token,cap,ack==1,name);if(!ValidSocialCommand(n))return false;v=n;return true;}
    public static NetDataWriter Write(SocialResult v){if(v.Operation is 0 or >long.MaxValue||!Enum.IsDefined(v.Outcome))throw new ArgumentException("Invalid social result.");var w=CreateWriter(NetworkMessageType.SocialResult);w.Put(v.Operation);w.Put(v.Tick);w.Put((byte)v.Outcome);return w;}
    public static bool TryReadSocialResult(NetDataReader r,out SocialResult v){v=default;if(r.AvailableBytes!=13||!r.TryGetULong(out var op)||op is 0 or >long.MaxValue||!r.TryGetUInt(out var tick)||!r.TryGetByte(out var outcome)||!Enum.IsDefined((SocialOutcome)outcome))return false;v=new(op,tick,(SocialOutcome)outcome);return true;}
    private static bool ValidRoster(SocialRoster v)=>v.Owner.IsValid&&v.Self is >0 and <=long.MaxValue&&v.LastOperation<=long.MaxValue&&Enum.IsDefined(v.Kind)&&v.Id<=long.MaxValue&&v.Revision<=long.MaxValue&&SocialText(v.Name)&&v.Total<=(v.Kind==SocialKind.Party?20:32)&&v.Page<4&&v.Members is {Length:<=8}&&v.Members.All(m=>m.Handle is >0 and <=long.MaxValue&&Enum.IsDefined(m.Role))&&v.Members.Select(m=>m.Handle).Distinct().Count()==v.Members.Length&&(v.Id==0?v.Revision==0&&v.Leader==0&&v.Total==0&&v.Page==0&&v.Members.Length==0&&v.Capacity==0&&v.Name.Length==0:v.Revision>0&&v.Leader is >0 and <=long.MaxValue&&v.Total>0&&v.Total<=v.Capacity&&(v.Kind==SocialKind.Guild?v.Capacity==32:v.Capacity is 6 or 20)&&v.Page*8<v.Total&&v.Members.Length==Math.Min(8,v.Total-v.Page*8));
    public static NetDataWriter Write(SocialRoster v){if(!ValidRoster(v))throw new ArgumentException("Invalid social roster.");var w=CreateWriter(NetworkMessageType.SocialRoster);w.Put(v.Owner.Value);w.Put(v.Tick);w.Put(v.Self);w.Put(v.LastOperation);w.Put((byte)v.Kind);w.Put(v.Id);w.Put(v.Revision);w.Put(v.Capacity);w.Put(v.Leader);w.Put(v.Name);w.Put(v.Page);w.Put(v.Total);w.Put((byte)v.Members.Length);foreach(var m in v.Members){w.Put(m.Handle);w.Put((byte)m.Role);w.Put(m.Online);}return w;}
    public static bool TryReadSocialRoster(NetDataReader r,out SocialRoster v){v=default;if(r.AvailableBytes>240||!r.TryGetULong(out var owner)||!r.TryGetUInt(out var tick)||!r.TryGetULong(out var self)||!r.TryGetULong(out var op)||!r.TryGetByte(out var kind)||!r.TryGetULong(out var id)||!r.TryGetULong(out var rev)||!r.TryGetByte(out var cap)||!r.TryGetULong(out var leader)||!r.TryGetString(out var name)||!r.TryGetByte(out var page)||!r.TryGetByte(out var total)||!r.TryGetByte(out var count)||count>8)return false;var members=new SocialMember[count];for(var i=0;i<count;i++){if(!r.TryGetULong(out var h)||!r.TryGetByte(out var role)||!r.TryGetByte(out var online)||online>1)return false;members[i]=new(h,(SocialRole)role,online==1);}if(r.AvailableBytes!=0)return false;var n=new SocialRoster(new(owner),tick,self,op,(SocialKind)kind,id,rev,cap,leader,name,page,total,members);if(!ValidRoster(n))return false;v=n;return true;}
    public static NetDataWriter Write(SocialInvites v){if(!v.Owner.IsValid||v.Items is null||v.Items.Length>2||v.Items.Select(i=>i.Token).Distinct().Count()!=v.Items.Length||v.Items.Any(i=>i.Token is 0 or >long.MaxValue||!Enum.IsDefined(i.Kind)||i.From is 0 or >long.MaxValue||i.Id is 0 or >long.MaxValue||i.Revision is 0 or >long.MaxValue||!SocialText(i.Name)||!float.IsFinite(i.Seconds)||i.Seconds is <=0 or >30))throw new ArgumentException("Invalid invitations.");var w=CreateWriter(NetworkMessageType.SocialInvites);w.Put(v.Owner.Value);w.Put(v.Tick);w.Put((byte)v.Items.Length);foreach(var i in v.Items){w.Put(i.Token);w.Put((byte)i.Kind);w.Put(i.From);w.Put(i.Id);w.Put(i.Revision);w.Put(i.Name);w.Put(i.Handoff);w.Put(i.Seconds);}return w;}
    public static bool TryReadSocialInvites(NetDataReader r,out SocialInvites v){v=default;if(r.AvailableBytes>306||!r.TryGetULong(out var owner)||owner==0||!r.TryGetUInt(out var tick)||!r.TryGetByte(out var count)||count>2)return false;var items=new SocialInvite[count];for(var i=0;i<count;i++){if(!r.TryGetULong(out var token)||token is 0 or >long.MaxValue||!r.TryGetByte(out var kind)||!Enum.IsDefined((SocialKind)kind)||!r.TryGetULong(out var from)||from is 0 or >long.MaxValue||!r.TryGetULong(out var id)||id is 0 or >long.MaxValue||!r.TryGetULong(out var revision)||revision is 0 or >long.MaxValue||!r.TryGetString(out var name)||!SocialText(name)||!r.TryGetByte(out var handoff)||handoff>1||!r.TryGetFloat(out var seconds)||!float.IsFinite(seconds)||seconds is <=0 or >30)return false;items[i]=new(token,(SocialKind)kind,from,id,revision,name,handoff==1,seconds);}if(r.AvailableBytes!=0||items.Select(i=>i.Token).Distinct().Count()!=count)return false;v=new(new(owner),tick,items);return true;}
    private static bool ValidPresence(PartyPresence v)=>v.Owner.IsValid&&v.Party is >0 and <=long.MaxValue&&v.Revision is >0 and <=long.MaxValue&&v.Page<3&&v.Members is {Length:>0 and <=8}&&v.Members.Select(m=>m.Handle).Distinct().Count()==v.Members.Length&&v.Members.All(m=>m.Handle is >0 and <=long.MaxValue&&m.Flags<=7&&float.IsFinite(m.Health)&&float.IsFinite(m.MaxHealth)&&m.Health>=0&&m.MaxHealth>=m.Health&&float.IsFinite(m.Position.X)&&float.IsFinite(m.Position.Y)&&(m.Flags&1)!=0||m.Handle is >0 and <=long.MaxValue&&m.Flags<=7&&(m.Flags&1)==0&&m.Health==0&&m.MaxHealth==0&&m.Position==Vector2.Zero);
    public static NetDataWriter Write(PartyPresence v){if(!ValidPresence(v))throw new ArgumentException("Invalid party presence.");var w=CreateWriter(NetworkMessageType.PartyPresence);w.Put(v.Owner.Value);w.Put(v.Tick);w.Put(v.Party);w.Put(v.Revision);w.Put(v.Page);w.Put((byte)v.Members.Length);foreach(var m in v.Members){w.Put(m.Handle);w.Put(m.Flags);w.Put(m.Health);w.Put(m.MaxHealth);w.Put(m.Position.X);w.Put(m.Position.Y);}return w;}
    public static bool TryReadPartyPresence(NetDataReader r,out PartyPresence v){v=default;if(r.AvailableBytes>230||!r.TryGetULong(out var owner)||!r.TryGetUInt(out var tick)||!r.TryGetULong(out var party)||!r.TryGetULong(out var rev)||!r.TryGetByte(out var page)||!r.TryGetByte(out var count)||count is 0 or >8)return false;var members=new PartyMemberPresence[count];for(var i=0;i<count;i++){if(!r.TryGetULong(out var h)||!r.TryGetByte(out var flags)||!r.TryGetFloat(out var hp)||!r.TryGetFloat(out var max)||!r.TryGetFloat(out var x)||!r.TryGetFloat(out var z))return false;members[i]=new(h,flags,hp,max,new(x,z));}if(r.AvailableBytes!=0)return false;var n=new PartyPresence(new(owner),tick,party,rev,page,members);if(!ValidPresence(n))return false;v=n;return true;}
}
