namespace Content.Shared.Network;

public enum NetworkMessageType : ushort
{
    ClientHello = 1,
    ServerWelcome = 2,
    ServerReject = 3,
    PlayerSpawn = 10,
    PlayerDespawn = 11,
    MoveCommand = 12,
    WorldSnapshot = 13,
    RegionNavigation = 14,
    AttackCommand = 15,
    AttackResult = 16,
    AttackEvent = 17,
    CombatState = 18,
    AbilityCommand = 19,
    AbilityResult = 20,
    AbilityLoadout = 21,
    AbilityEffectState = 22,
    AbilityHit = 23,
    NpcWindup = 24,
    NpcArea = 25,
    InventoryCommand = 26,
    InventoryResult = 27,
    InventoryState = 28,
    PickupCommand = 29,
    PickupResult = 30,
    GroundItemSpawn = 31,
    GroundItemDespawn = 32,
    DevelopmentRevive = 33,
    DevelopmentTools = 34,
    EchoSpawn = 35,
    EchoSignatureCommand = 36,
    EchoSignatureResult = 37,
    EchoAction = 38,
    EchoLoadout = 39,
    ProgressionCommand = 40,
    ProgressionState = 41,
    ProgressionResult = 42,
    ProfessionCommand = 43,
    ProfessionState = 44,
    CraftCommand = 51, CraftResult = 52, CraftState = 53, ResourceNodeState = 54, ResourceNodeDespawn = 55, CraftRecipeState = 56,
    RepairCommand = 57, RepairQuote = 58, RepairResult = 59, ItemConditionState = 60, TradeCommand = 61, TradeState = 62, TradeResult = 63,
    StarterZoneState = 49,
    ExplorationState = 50,
    WorldNodeCommand = 46,
    WorldNodeState = 47,
    WorldNodeResult = 48,
    ProfessionResult = 45,
    EconomyCommand = 64,
    EconomyQuote = 65,
    EconomyResult = 66,
    EconomyState = 67,
    MarketState = 68,
    PvpCommand = 69,
    PvpResult = 70,
    PvpPublicState = 71,
    PvpState = 72,
    PickupChannelState = 73,
    PvpZoneState = 74,
    PvpLootState = 75,
    SocialCommand = 76, SocialResult = 77, SocialRoster = 78, SocialInvites = 79, PartyPresence = 80,
    RegionEnter = 81,
    RegionPacket = 82,
}
