using LiteNetLib.Utils;
namespace Content.Shared.Network;
public static partial class NetworkProtocol
{
    public static bool ValidPvpCommand(PvpCommand v)=>v.Sequence is >0 and <=long.MaxValue&&Enum.IsDefined(v.Action)&&Enum.IsDefined(v.Mode)&&v.DeathId<=long.MaxValue&&(v.Action==PvpAction.Mode?v.DeathId==0&&(v.Mode!=PvpMode.Criminal||v.Acknowledge):v.DeathId>0&&v.Mode==PvpMode.Peaceful&&!v.Acknowledge);
    public static NetDataWriter Write(PvpCommand v){if(!ValidPvpCommand(v))throw new ArgumentException("Invalid PvP command.");var w=CreateWriter(NetworkMessageType.PvpCommand);w.Put(v.Sequence);w.Put((byte)v.Action);w.Put((byte)v.Mode);w.Put(v.Acknowledge);w.Put(v.DeathId);return w;}
    public static bool TryReadPvpCommand(NetDataReader r,out PvpCommand v){v=default;if(r.AvailableBytes!=19||!r.TryGetULong(out var seq)||!r.TryGetByte(out var action)||!r.TryGetByte(out var mode)||!r.TryGetByte(out var ack)||ack>1||!r.TryGetULong(out var death))return false;var n=new PvpCommand(seq,(PvpAction)action,(PvpMode)mode,ack==1,death);if(!ValidPvpCommand(n))return false;v=n;return true;}
    public static NetDataWriter Write(PvpResult v){if(v.Sequence is 0 or >long.MaxValue||!Enum.IsDefined(v.Outcome))throw new ArgumentException("Invalid PvP result.");var w=CreateWriter(NetworkMessageType.PvpResult);w.Put(v.Sequence);w.Put(v.ServerTick);w.Put((byte)v.Outcome);return w;}
    public static bool TryReadPvpResult(NetDataReader r,out PvpResult v){v=default;if(r.AvailableBytes!=13||!r.TryGetULong(out var seq)||seq is 0 or >long.MaxValue||!r.TryGetUInt(out var tick)||!r.TryGetByte(out var outcome)||!Enum.IsDefined((PvpOutcome)outcome))return false;v=new(seq,tick,(PvpOutcome)outcome);return true;}
    private static byte Flags(bool a,bool b,bool c,bool d)=>(byte)((a?1:0)|(b?2:0)|(c?4:0)|(d?8:0));
    public static NetDataWriter Write(PvpPublicState v){if(!v.EntityId.IsValid||!Enum.IsDefined(v.Mode))throw new ArgumentException("Invalid PvP flags.");var w=CreateWriter(NetworkMessageType.PvpPublicState);w.Put(v.EntityId.Value);w.Put(v.ServerTick);w.Put((byte)v.Mode);w.Put(Flags(v.Tagged,v.Aggressor,v.Protected,v.Dead));return w;}
    public static bool TryReadPvpPublicState(NetDataReader r,out PvpPublicState v){v=default;if(r.AvailableBytes!=14||!r.TryGetULong(out var id)||id==0||!r.TryGetUInt(out var tick)||!r.TryGetByte(out var mode)||!Enum.IsDefined((PvpMode)mode)||!r.TryGetByte(out var flags)||flags>15)return false;v=new(new(id),tick,(PvpMode)mode,(flags&1)!=0,(flags&2)!=0,(flags&4)!=0,(flags&8)!=0);return true;}
    private static bool Seconds(float v,float limit)=>float.IsFinite(v)&&v>=0&&v<=limit;
    private static bool ValidPvpState(PvpState v)=>v.OwnerId.IsValid&&v.LastSequence<=long.MaxValue&&Enum.IsDefined(v.Mode)&&v.Reputation is >=-1000 and <=1000&&v.Pk>=0&&v.DeathId<=long.MaxValue&&(!v.Dead||v.DeathId>0)&&v.ExperienceLost is >=0 and <=1000000000&&Seconds(v.RespawnSeconds,60)&&Seconds(v.CombatSeconds,120)&&Seconds(v.AggressorSeconds,600);
    public static NetDataWriter Write(PvpState v){if(!ValidPvpState(v))throw new ArgumentException("Invalid private PvP state.");var w=CreateWriter(NetworkMessageType.PvpState);w.Put(v.OwnerId.Value);w.Put(v.ServerTick);w.Put(v.LastSequence);w.Put((byte)v.Mode);w.Put(v.Reputation);w.Put(v.Pk);w.Put(v.DeathId);w.Put(Flags(v.Dead,v.PvpDeath,v.Dropped,v.DropSkipped));w.Put(v.RespawnSeconds);w.Put(v.ExperienceLost);w.Put(v.CombatSeconds);w.Put(v.AggressorSeconds);return w;}
    public static bool TryReadPvpState(NetDataReader r,out PvpState v){v=default;if(r.AvailableBytes!=54||!r.TryGetULong(out var id)||!r.TryGetUInt(out var tick)||!r.TryGetULong(out var seq)||!r.TryGetByte(out var mode)||!r.TryGetInt(out var rep)||!r.TryGetInt(out var pk)||!r.TryGetULong(out var death)||!r.TryGetByte(out var flags)||flags>15||!r.TryGetFloat(out var respawn)||!r.TryGetInt(out var xp)||!r.TryGetFloat(out var combat)||!r.TryGetFloat(out var aggressor))return false;var n=new PvpState(new(id),tick,seq,(PvpMode)mode,rep,pk,death,(flags&1)!=0,(flags&2)!=0,respawn,xp,(flags&4)!=0,(flags&8)!=0,combat,aggressor);if(!ValidPvpState(n))return false;v=n;return true;}
    public static NetDataWriter Write(PickupChannelState v){if(!v.OwnerId.IsValid||!Seconds(v.RemainingSeconds,5)||(v.Handle==0)!=(v.RemainingSeconds==0))throw new ArgumentException("Invalid pickup channel.");var w=CreateWriter(NetworkMessageType.PickupChannelState);w.Put(v.OwnerId.Value);w.Put(v.ServerTick);w.Put(v.Handle);w.Put(v.RemainingSeconds);return w;}
    public static bool TryReadPickupChannelState(NetDataReader r,out PickupChannelState v){v=default;if(r.AvailableBytes!=24||!r.TryGetULong(out var id)||id==0||!r.TryGetUInt(out var tick)||!r.TryGetULong(out var handle)||!r.TryGetFloat(out var seconds)||!Seconds(seconds,5)||(handle==0)!=(seconds==0))return false;v=new(new(id),tick,handle,seconds);return true;}
}
public static partial class NetworkProtocol
{
    public static NetDataWriter Write(PvpZoneState v){if(!float.IsFinite(v.MinX)||!float.IsFinite(v.MaxX)||!float.IsFinite(v.MinZ)||!float.IsFinite(v.MaxZ)||v.MinX>=v.MaxX||v.MinZ>=v.MaxZ)throw new ArgumentException("Invalid safe zone.");var w=CreateWriter(NetworkMessageType.PvpZoneState);w.Put(v.MinX);w.Put(v.MaxX);w.Put(v.MinZ);w.Put(v.MaxZ);return w;}
    public static bool TryReadPvpZoneState(NetDataReader r,out PvpZoneState v){v=default;if(r.AvailableBytes!=16||!r.TryGetFloat(out var x)||!r.TryGetFloat(out var X)||!r.TryGetFloat(out var z)||!r.TryGetFloat(out var Z)||!float.IsFinite(x)||!float.IsFinite(X)||!float.IsFinite(z)||!float.IsFinite(Z)||x>=X||z>=Z)return false;v=new(x,X,z,Z);return true;}
    public static NetDataWriter Write(PvpLootState v){if(v.Handle==0||!Seconds(v.RemainingSeconds,1800))throw new ArgumentException("Invalid loot lifetime.");var w=CreateWriter(NetworkMessageType.PvpLootState);w.Put(v.Handle);w.Put(v.RemainingSeconds);return w;}
    public static bool TryReadPvpLootState(NetDataReader r,out PvpLootState v){v=default;if(r.AvailableBytes!=12||!r.TryGetULong(out var h)||h==0||!r.TryGetFloat(out var s)||!Seconds(s,1800))return false;v=new(h,s);return true;}
}
