<Project Sdk="Godot.NET.Sdk/4.7.1">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>ProjectG.BalanceStudio</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Balance.Core/Balance.Core.csproj" />
  </ItemGroup>
</Project>
