using Content.Server.Persistence;
using Content.Shared.Network;
using Content.Tests.Server.Persistence;
using Xunit;
namespace Content.Tests.Server;
public sealed class EconomyPersistenceTests
{
    [Fact] public async Task EscrowAndOfflineProceedsSurviveSqliteRestartThenClaimExactlyOnce()
    {
        var store=new SqliteCharacterStore();await store.InitializeAsync(CancellationToken.None);var w=CraftingTests.World();var initial=EconomyTests.Initial(w);var seller=await store.OpenAsync("",initial,CancellationToken.None);var sellerToken=seller.IssuedToken;var uuid=seller.State.Inventory!.Items[0].InstanceId;var world=await store.OpenWorldAsync(w.WorldNodeKey,w.CaptureWorldNode(),CancellationToken.None);w.RestoreWorldNode(world.State,world.Revision);w.AddPlayer(42,new(1),seller.State);w.BindWorldActor(42,seller.CharacterId);
        EconomyTests.Execute(w,42,EconomyTests.Command(w,42,1,EconomyAction.List,price:10));await store.SaveWithWorldAsync([new(seller,w.CaptureCharacter(42))],new(world,w.CaptureWorldNode(),w.WorldNodeAudit),CancellationToken.None);await seller.DisposeAsync();await world.DisposeAsync();
        store=new SqliteCharacterStore(store.DatabasePath);await store.InitializeAsync(CancellationToken.None);w=CraftingTests.World();world=await store.OpenWorldAsync(w.WorldNodeKey,w.CaptureWorldNode(),CancellationToken.None);w.RestoreWorldNode(world.State,world.Revision);var buyerInitial=EconomyTests.Initial(w,coins:20);var buyer=await store.OpenAsync("",buyerInitial,CancellationToken.None);var buyerToken=buyer.IssuedToken;w.AddPlayer(43,new(2),buyer.State);w.BindWorldActor(43,buyer.CharacterId);var listing=Assert.Single(w.CaptureWorldNode().Market!.Listings);Assert.Equal(uuid,listing.Item.InstanceId);
        EconomyTests.Execute(w,43,EconomyTests.Command(w,43,1,EconomyAction.Buy,listing:listing.Id));await store.SaveWithWorldAsync([new(buyer,w.CaptureCharacter(43))],new(world,w.CaptureWorldNode(),w.WorldNodeAudit),CancellationToken.None);await buyer.DisposeAsync();await world.DisposeAsync();
        store=new SqliteCharacterStore(store.DatabasePath);await store.InitializeAsync(CancellationToken.None);w=CraftingTests.World();world=await store.OpenWorldAsync(w.WorldNodeKey,w.CaptureWorldNode(),CancellationToken.None);w.RestoreWorldNode(world.State,world.Revision);buyer=await store.OpenAsync(buyerToken,buyerInitial,CancellationToken.None);Assert.Single(buyer.State.Inventory!.Items,i=>i.InstanceId==uuid);Assert.Equal(10,buyer.State.Inventory.Economy!.Coins);await buyer.DisposeAsync();seller=await store.OpenAsync(sellerToken,initial,CancellationToken.None);Assert.Empty(seller.State.Inventory!.Items);Assert.Equal(0,seller.State.Inventory.Economy!.Coins);Assert.Equal(10,Assert.Single(world.State.Market!.Credits).Coins);w.AddPlayer(42,new(1),seller.State);w.BindWorldActor(42,seller.CharacterId);var claim=EconomyTests.Quote(w,42,EconomyTests.Command(w,42,2,EconomyAction.Claim));EconomyTests.Confirm(w,42,claim.Command);await store.SaveWithWorldAsync([new(seller,w.CaptureCharacter(42))],new(world,w.CaptureWorldNode(),w.WorldNodeAudit),CancellationToken.None);await seller.DisposeAsync();await world.DisposeAsync();
        store=new SqliteCharacterStore(store.DatabasePath);await store.InitializeAsync(CancellationToken.None);w=CraftingTests.World();world=await store.OpenWorldAsync(w.WorldNodeKey,w.CaptureWorldNode(),CancellationToken.None);w.RestoreWorldNode(world.State,world.Revision);seller=await store.OpenAsync(sellerToken,initial,CancellationToken.None);w.AddPlayer(42,new(1),seller.State);w.BindWorldActor(42,seller.CharacterId);Assert.Equal(CraftOutcome.AlreadyProcessed,EconomyTests.Confirm(w,42,claim.Command).Outcome);Assert.Equal(10,w.CaptureCharacter(42).Inventory!.Economy!.Coins);Assert.Empty(w.CaptureWorldNode().Market!.Credits);await seller.DisposeAsync();await world.DisposeAsync();
    }
    [Fact] public async Task WorldFenceFailureRollsBackListingReceiptInventoryAndOwnership()
    {
        var store=new SqliteCharacterStore();await store.InitializeAsync(CancellationToken.None);var w=CraftingTests.World();var initial=EconomyTests.Initial(w);var owner=await store.OpenAsync("",initial,CancellationToken.None);var token=owner.IssuedToken;var world=await store.OpenWorldAsync(w.WorldNodeKey,w.CaptureWorldNode(),CancellationToken.None);w.RestoreWorldNode(world.State,world.Revision);w.AddPlayer(42,new(1),owner.State);w.BindWorldActor(42,owner.CharacterId);
        await store.SaveWithWorldAsync([],new(world,world.State,[new("test","Fence","Advance",1)]),CancellationToken.None);EconomyTests.Execute(w,42,EconomyTests.Command(w,42,1,EconomyAction.List,price:10));await Assert.ThrowsAsync<InvalidOperationException>(()=>store.SaveWithWorldAsync([new(owner,w.CaptureCharacter(42))],new(world,w.CaptureWorldNode(),w.WorldNodeAudit),CancellationToken.None));await owner.DisposeAsync();await world.DisposeAsync();
        owner=await store.OpenAsync(token,initial,CancellationToken.None);Assert.Single(owner.State.Inventory!.Items);Assert.Equal(0UL,owner.State.Inventory.Economy!.LastOperation);await owner.DisposeAsync();world=await store.OpenWorldAsync(w.WorldNodeKey,new(),CancellationToken.None);Assert.Null(world.State.Market);await world.DisposeAsync();
    }
    [Fact] public async Task DestructionReceiptSurvivesRestartAndRemovedUuidCannotBeReissued()
    {
        var store=new SqliteCharacterStore();await store.InitializeAsync(CancellationToken.None);var w=CraftingTests.World();var initial=EconomyTests.Initial(w,10,4);var owner=await store.OpenAsync("",initial,CancellationToken.None);var token=owner.IssuedToken;w.AddPlayer(42,new(1),owner.State);w.Inventory!.EnhancementRoll=()=>99;var quote=EconomyTests.Quote(w,42,EconomyTests.Command(w,42,1,EconomyAction.Enhance));Assert.Equal(EconomyEffect.Destroyed,EconomyTests.Confirm(w,42,quote.Command).Effect);await store.SaveAsync([new(owner,w.CaptureCharacter(42))],CancellationToken.None);await owner.DisposeAsync();
        store=new SqliteCharacterStore(store.DatabasePath);await store.InitializeAsync(CancellationToken.None);owner=await store.OpenAsync(token,initial,CancellationToken.None);w=CraftingTests.World();w.AddPlayer(42,new(1),owner.State);w.Inventory!.EnhancementRoll=()=>throw new Exception("Persisted result must not reroll");Assert.Equal(EconomyEffect.Destroyed,EconomyTests.Confirm(w,42,quote.Command).Effect);Assert.Empty(w.CaptureCharacter(42).Inventory!.Items);Assert.Equal(19,w.CaptureCharacter(42).Inventory!.Crafting!.Materials.Single(m=>m.Id==3).Quantity);await owner.DisposeAsync();await Assert.ThrowsAsync<InvalidOperationException>(()=>store.OpenAsync("",initial,CancellationToken.None));
    }
}
